import { defineConfig } from "tinacms";

// Your hosting provider likely exposes this as an environment variable
const branch =
  process.env.VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,

  // Get this from tina.io
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID || "d68f56a4-25d9-4abc-8f61-0236724469c9",
  // Get this from tina.io
  token: process.env.TINA_TOKEN || "9fc539a544350030c9a4e49fbafd104f8af06564",

  build: {
    outputFolder: "admin",
    publicFolder: "",
  },
  // Uncomment to allow cross-origin requests from non-localhost origins
  // during local development (e.g. GitHub Codespaces, Gitpod, Docker).
  // Use 'private' to allow all private-network IPs (WSL2, Docker, etc.)
  // server: {
  //   allowedOrigins: ['https://your-codespace.github.dev'],
  // },
  media: {
    tina: {
      mediaRoot: "",
      publicFolder: ".",
    },
  },
  // See docs on content modeling for more info on how to setup new content models: https://tina.io/docs/r/content-modelling-collections/
  schema: {
    collections: [
      {
        name: "global",
        label: "Configurações Globais",
        path: "content/data",
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        match: { include: "info" },
        fields: [
          { type: "string", name: "phoneLabel", label: "Telefone de Exibição" },
          { type: "string", name: "phoneWhatsapp", label: "Número do WhatsApp (apenas números)" },
          { type: "string", name: "email", label: "E-mail" },
          { type: "string", name: "address", label: "Endereço Físico" },
          { type: "string", name: "footerText", label: "Texto do Rodapé (Sobre a empresa)", ui: { component: "textarea" } },
          { type: "string", name: "footerCopyright", label: "Copyright do Rodapé" },
        ],
      },
      {
        name: "home",
        label: "Página Inicial",
        path: "content/pages",
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        match: { include: "home" },
        fields: [
          { type: "string", name: "heroTitle", label: "Título Principal (Hero)" },
          { type: "string", name: "heroDescription", label: "Descrição (Hero)", ui: { component: "textarea" } },
          { type: "image", name: "heroImage", label: "Vídeo/Imagem da Seção Hero" },
          { type: "string", name: "heroBtn1", label: "Botão Hero 1" },
          { type: "string", name: "heroBtn2", label: "Botão Hero 2" },
          { type: "image", name: "aboutImage", label: "Imagem (Resumo Sobre)" },
          { type: "string", name: "aboutBadgeNum", label: "Número Badge (Sobre)" },
          { type: "string", name: "aboutBadgeText", label: "Texto Badge (Sobre)" },
          { type: "string", name: "aboutTag", label: "Tag (Sobre)" },
          { type: "string", name: "aboutTitle", label: "Título (Sobre)" },
          { type: "string", name: "aboutLead", label: "Texto Lead (Sobre)", ui: { component: "textarea" } },
          { type: "string", name: "aboutFeature1Title", label: "Feature 1 Título (Sobre)" },
          { type: "string", name: "aboutFeature1Desc", label: "Feature 1 Desc (Sobre)", ui: { component: "textarea" } },
          { type: "string", name: "aboutFeature2Title", label: "Feature 2 Título (Sobre)" },
          { type: "string", name: "aboutFeature2Desc", label: "Feature 2 Desc (Sobre)", ui: { component: "textarea" } },
          { type: "string", name: "aboutFeature3Title", label: "Feature 3 Título (Sobre)" },
          { type: "string", name: "aboutFeature3Desc", label: "Feature 3 Desc (Sobre)", ui: { component: "textarea" } },
          { type: "string", name: "aboutBtn", label: "Botão (Sobre)" },
          { type: "string", name: "servicesTag", label: "Tag (Resumo Serviços)" },
          { type: "string", name: "servicesTitle", label: "Título (Resumo Serviços)" },
          { type: "string", name: "servicesLead", label: "Texto Descritivo (Resumo Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem1Title", label: "Item 1 Título (Serviços)" },
          { type: "string", name: "servicesItem1Desc", label: "Item 1 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem2Title", label: "Item 2 Título (Serviços)" },
          { type: "string", name: "servicesItem2Desc", label: "Item 2 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem3Title", label: "Item 3 Título (Serviços)" },
          { type: "string", name: "servicesItem3Desc", label: "Item 3 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem4Title", label: "Item 4 Título (Serviços)" },
          { type: "string", name: "servicesItem4Desc", label: "Item 4 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem5Title", label: "Item 5 Título (Serviços)" },
          { type: "string", name: "servicesItem5Desc", label: "Item 5 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesItem6Title", label: "Item 6 Título (Serviços)" },
          { type: "string", name: "servicesItem6Desc", label: "Item 6 Desc (Serviços)", ui: { component: "textarea" } },
          { type: "string", name: "servicesBtn", label: "Botão (Resumo Serviços)" },
          { type: "string", name: "ctaPmocTitle", label: "Título (CTA PMOC)" },
          { type: "string", name: "ctaPmocDesc", label: "Descrição (CTA PMOC)", ui: { component: "textarea" } },
          { type: "string", name: "ctaPmocBtn", label: "Botão (CTA PMOC)" },
        ],
      },
      {
        name: "sobre",
        label: "Página A Empresa",
        path: "content/pages",
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        match: { include: "sobre" },
        fields: [
          { type: "string", name: "pageHeroTitle", label: "Título Page Hero" },
          { type: "string", name: "pageHeroDesc", label: "Descrição Page Hero", ui: { component: "textarea" } },
          { type: "image", name: "aboutMainImage", label: "Imagem Principal (Sobre)" },
          { type: "string", name: "aboutMainBadgeNum", label: "Número Badge" },
          { type: "string", name: "aboutMainBadgeText", label: "Texto Badge" },
          { type: "string", name: "aboutMainTag", label: "Tag Principal" },
          { type: "string", name: "aboutMainTitle", label: "Título Principal" },
          { type: "string", name: "aboutMainP1", label: "Parágrafo 1", ui: { component: "textarea" } },
          { type: "string", name: "aboutMainP2", label: "Parágrafo 2", ui: { component: "textarea" } },
          { type: "string", name: "aboutMainP3", label: "Parágrafo 3", ui: { component: "textarea" } },
          { type: "string", name: "valoresTag", label: "Tag (Pilares)" },
          { type: "string", name: "valoresTitle", label: "Título (Pilares)" },
          { type: "string", name: "valMissaoTitle", label: "Missão Título" },
          { type: "string", name: "valMissaoDesc", label: "Missão Desc", ui: { component: "textarea" } },
          { type: "string", name: "valVisaoTitle", label: "Visão Título" },
          { type: "string", name: "valVisaoDesc", label: "Visão Desc", ui: { component: "textarea" } },
          { type: "string", name: "valValoresTitle", label: "Valores Título" },
          { type: "string", name: "valValoresDesc", label: "Valores Desc", ui: { component: "textarea" } },
          { type: "string", name: "historiaTag", label: "Tag (Trajetória)" },
          { type: "string", name: "historiaTitle", label: "Título (Trajetória)" },
          { type: "string", name: "historiaLead", label: "Texto Descritivo (Trajetória)", ui: { component: "textarea" } },
          { type: "string", name: "tl1Year", label: "Timeline 1 Ano" },
          { type: "string", name: "tl1Title", label: "Timeline 1 Título" },
          { type: "string", name: "tl1Desc", label: "Timeline 1 Desc", ui: { component: "textarea" } },
          { type: "string", name: "tl2Year", label: "Timeline 2 Ano" },
          { type: "string", name: "tl2Title", label: "Timeline 2 Título" },
          { type: "string", name: "tl2Desc", label: "Timeline 2 Desc", ui: { component: "textarea" } },
          { type: "string", name: "tl3Year", label: "Timeline 3 Ano" },
          { type: "string", name: "tl3Title", label: "Timeline 3 Título" },
          { type: "string", name: "tl3Desc", label: "Timeline 3 Desc", ui: { component: "textarea" } },
          { type: "string", name: "tl4Year", label: "Timeline 4 Ano" },
          { type: "string", name: "tl4Title", label: "Timeline 4 Título" },
          { type: "string", name: "tl4Desc", label: "Timeline 4 Desc", ui: { component: "textarea" } },
          { type: "string", name: "tl5Year", label: "Timeline 5 Ano" },
          { type: "string", name: "tl5Title", label: "Timeline 5 Título" },
          { type: "string", name: "tl5Desc", label: "Timeline 5 Desc", ui: { component: "textarea" } },
          { type: "image", name: "historiaImage", label: "Imagem (Trajetória)" },
          { type: "string", name: "stat1Num", label: "Estatística 1 Número" },
          { type: "string", name: "stat1Label", label: "Estatística 1 Label" },
          { type: "string", name: "stat2Num", label: "Estatística 2 Número" },
          { type: "string", name: "stat2Label", label: "Estatística 2 Label" },
          { type: "string", name: "ctaTitle", label: "Título CTA Final" },
          { type: "string", name: "ctaDesc", label: "Descrição CTA Final", ui: { component: "textarea" } },
          { type: "string", name: "ctaBtn", label: "Botão CTA Final" },
        ],
      },
      {
        name: "servicos",
        label: "Página Serviços",
        path: "content/pages",
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        match: { include: "servicos" },
        fields: [
          { type: "string", name: "pageHeroTitle", label: "Título Page Hero" },
          { type: "string", name: "pageHeroDesc", label: "Descrição Page Hero", ui: { component: "textarea" } },
          { type: "image", name: "instImage", label: "Imagem Instalação" },
          { type: "string", name: "instTag", label: "Tag Instalação" },
          { type: "string", name: "instTitle", label: "Título Instalação" },
          { type: "string", name: "instDesc", label: "Descrição Instalação", ui: { component: "textarea" } },
          { type: "string", name: "instL1", label: "Instalação Item 1" },
          { type: "string", name: "instL2", label: "Instalação Item 2" },
          { type: "string", name: "instL3", label: "Instalação Item 3" },
          { type: "string", name: "instL4", label: "Instalação Item 4" },
          { type: "string", name: "instL5", label: "Instalação Item 5" },
          { type: "string", name: "instBtn", label: "Botão Instalação" },
          { type: "image", name: "prevImage", label: "Imagem Preventiva" },
          { type: "string", name: "prevTag", label: "Tag Preventiva" },
          { type: "string", name: "prevTitle", label: "Título Preventiva" },
          { type: "string", name: "prevDesc", label: "Descrição Preventiva", ui: { component: "textarea" } },
          { type: "string", name: "prevL1", label: "Preventiva Item 1" },
          { type: "string", name: "prevL2", label: "Preventiva Item 2" },
          { type: "string", name: "prevL3", label: "Preventiva Item 3" },
          { type: "string", name: "prevL4", label: "Preventiva Item 4" },
          { type: "string", name: "prevL5", label: "Preventiva Item 5" },
          { type: "string", name: "prevBtn", label: "Botão Preventiva" },
          { type: "image", name: "corrImage", label: "Imagem Corretiva" },
          { type: "string", name: "corrTag", label: "Tag Corretiva" },
          { type: "string", name: "corrTitle", label: "Título Corretiva" },
          { type: "string", name: "corrDesc", label: "Descrição Corretiva", ui: { component: "textarea" } },
          { type: "string", name: "corrL1", label: "Corretiva Item 1" },
          { type: "string", name: "corrL2", label: "Corretiva Item 2" },
          { type: "string", name: "corrL3", label: "Corretiva Item 3" },
          { type: "string", name: "corrL4", label: "Corretiva Item 4" },
          { type: "string", name: "corrL5", label: "Corretiva Item 5" },
          { type: "string", name: "corrBtn", label: "Botão Corretiva" },
          { type: "image", name: "pmocImage", label: "Imagem PMOC" },
          { type: "string", name: "pmocTopTag", label: "Tag Topo PMOC" },
          { type: "string", name: "pmocTopTitle", label: "Título Topo PMOC" },
          { type: "string", name: "pmocColTag", label: "Tag Coluna PMOC" },
          { type: "string", name: "pmocColTitle", label: "Título Coluna PMOC" },
          { type: "string", name: "pmocLawText", label: "Texto Lei PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocP1", label: "Parágrafo 1 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocP2", label: "Parágrafo 2 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBenTitle", label: "Título Benefícios PMOC" },
          { type: "string", name: "pmocBen1", label: "Benefício 1 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBen2", label: "Benefício 2 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBen3", label: "Benefício 3 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBen4", label: "Benefício 4 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBen5", label: "Benefício 5 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBen6", label: "Benefício 6 PMOC", ui: { component: "textarea" } },
          { type: "string", name: "pmocBtn", label: "Botão PMOC" },
          { type: "image", name: "higiImage", label: "Imagem Higienização" },
          { type: "string", name: "higiTag", label: "Tag Higienização" },
          { type: "string", name: "higiTitle", label: "Título Higienização" },
          { type: "string", name: "higiDesc", label: "Descrição Higienização", ui: { component: "textarea" } },
          { type: "string", name: "higiL1", label: "Higienização Item 1" },
          { type: "string", name: "higiL2", label: "Higienização Item 2" },
          { type: "string", name: "higiL3", label: "Higienização Item 3" },
          { type: "string", name: "higiL4", label: "Higienização Item 4" },
          { type: "string", name: "higiL5", label: "Higienização Item 5" },
          { type: "string", name: "higiBtn", label: "Botão Higienização" },
          { type: "image", name: "projImage", label: "Imagem Projetos" },
          { type: "string", name: "projTag", label: "Tag Projetos" },
          { type: "string", name: "projTitle", label: "Título Projetos" },
          { type: "string", name: "projDesc", label: "Descrição Projetos", ui: { component: "textarea" } },
          { type: "string", name: "projL1", label: "Projetos Item 1" },
          { type: "string", name: "projL2", label: "Projetos Item 2" },
          { type: "string", name: "projL3", label: "Projetos Item 3" },
          { type: "string", name: "projL4", label: "Projetos Item 4" },
          { type: "string", name: "projL5", label: "Projetos Item 5" },
          { type: "string", name: "projBtn", label: "Botão Projetos" },
          { type: "string", name: "ctaTitle", label: "Título CTA Final" },
          { type: "string", name: "ctaDesc", label: "Descrição CTA Final", ui: { component: "textarea" } },
          { type: "string", name: "ctaBtn", label: "Botão CTA Final" },
        ],
      },
      {
        name: "contato",
        label: "Página Contato",
        path: "content/pages",
        format: "json",
        ui: { allowedActions: { create: false, delete: false } },
        match: { include: "contato" },
        fields: [
          { type: "string", name: "pageHeroTitle", label: "Título Page Hero" },
          { type: "string", name: "pageHeroDesc", label: "Descrição Page Hero", ui: { component: "textarea" } },
          { type: "string", name: "wppBarText", label: "Texto Barra WhatsApp" },
          { type: "string", name: "wppBarBtn", label: "Botão Barra WhatsApp" },
          { type: "string", name: "contatoTag", label: "Tag Contato Principal" },
          { type: "string", name: "contatoTitle", label: "Título Contato Principal" },
          { type: "string", name: "horarioL1", label: "Horário Linha 1" },
          { type: "string", name: "horarioL2", label: "Horário Linha 2" },
          { type: "string", name: "horarioL3", label: "Horário Linha 3" },
          { type: "string", name: "formTitle", label: "Título Formulário" },
          { type: "string", name: "formDesc", label: "Descrição Formulário", ui: { component: "textarea" } },
          { type: "string", name: "faqTag", label: "Tag FAQ" },
          { type: "string", name: "faqTitle", label: "Título FAQ" },
          { type: "string", name: "faq1Q", label: "FAQ 1 Pergunta" },
          { type: "string", name: "faq1A", label: "FAQ 1 Resposta", ui: { component: "textarea" } },
          { type: "string", name: "faq2Q", label: "FAQ 2 Pergunta" },
          { type: "string", name: "faq2A", label: "FAQ 2 Resposta", ui: { component: "textarea" } },
          { type: "string", name: "faq3Q", label: "FAQ 3 Pergunta" },
          { type: "string", name: "faq3A", label: "FAQ 3 Resposta", ui: { component: "textarea" } },
          { type: "string", name: "faq4Q", label: "FAQ 4 Pergunta" },
          { type: "string", name: "faq4A", label: "FAQ 4 Resposta", ui: { component: "textarea" } },
        ],
      }
    ],
  },
});
